apiVersion: v1
kind: Service
metadata:
  name: appointment-management-service
spec:
  selector:
    app: appointment-management  # This matches the label of the appointment-management pod
  ports:
    - protocol: TCP
      port: 80  # Expose externally on port 80
      targetPort: 5003  # Map to the internal port 5003 in the container
  type: LoadBalancer  # Useful for cloud environments
