apiVersion: v1
kind: Service
metadata:
  name: location-service
spec:
  selector:
    app: location  # This matches the label of the location pod
  ports:
    - protocol: TCP
      port: 80  # Expose externally on port 80
      targetPort: 5002  # Map to the internal port 5002 in the container
  type: LoadBalancer  # Useful for cloud environments
