# apiVersion: v1
# kind: Service
# metadata:
#   name: location-service
# spec:
#   selector:
#     app: location  # This matches the label of the location pod
#   ports:
#     - protocol: TCP
#       port: 80  # Expose externally on port 80
#       targetPort: 5002  # Map to the internal port 5002 in the container
#   type: LoadBalancer  # Useful for cloud environments
apiVersion: v1
kind: Service
metadata:
  name: location-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '80'       # Service port (not targetPort)
    prometheus.io/path: '/metrics' # Metrics endpoint
spec:
  selector:
    app: location
  ports:
    - port: 80          # Service port
      targetPort: 5002  # Pod port
  type: LoadBalancer
